# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e43e93ae6c689b6f8c293a75aedd517cd84660633ba4e8903c9f8a33c0bcfe0cdb5e435122c5cc01428882543bf68473fc9a0ee3fd980500fc2bc1f75aea2f

test:
  secret_key_base: d28970e9ba45efea3c2d4d29312072d89f0102fd4fede276037a9f71bc090942ecb3abeabd85a949fac5265da0248221b4dfd89b523ada104de196ab5eed98d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
